#!/usr/bin/env zsh

STOW_FOLDERS='gitconfig,tmux,zsh,nvim, "cht.sh"'

DOTFILES_HOME="$HOME/.dotfiles"

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
	echo "Adding $folder"
	stow $folder -t $HOME -v
done
popd
