#!/usr/bin/env zsh

STOW_FOLDERS='zsh,mamba,nvim,starship,i3,tmux,kitty,bin,clangd'

DOTFILES_HOME="$HOME/.dotfiles"

pushd $DOTFILES_HOME
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
	echo "Adding $folder"
	stow $folder -t $HOME -v
done
popd
