#!/usr/bin/env zsh

STOW_FOLDERS='zsh,conda'

DOTFILES_HOME="$HOME/.dotfiles"

pushd $DOTFILES_HOME
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
	echo "Adding $folder"
	stow $folder -t $HOME -v
done
popd
