#!/usr/bin/env bash

STOW_FOLDERS='zsh,mamba,nvim,starship,i3,tmux,kitty,bin'

DOTFILES_HOME="$HOME/.dotfiles"

pushd "$DOTFILES_HOME"
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
    echo "Removing $folder"
    stow -D $folder -v
done
popd
