#!/usr/bin/env zsh

STOW_FOLDERS='gitconfig,tmux,nvim,zsh,"cht.sh"'

DOTFILES_HOME=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
    echo "Removing $folder"
    stow -D $folder -v
done
popd
