#!/usr/bin/env bash

STOW_FOLDERS='zsh,mamba,nvim,starship,claude,gemini,hyprland,alacritty,tmux'

DOTFILES_HOME="$HOME/.dotfiles"

pushd "$DOTFILES_HOME"
for folder in $(echo $STOW_FOLDERS | sed 's/,/ /g')
do
    echo "Removing $folder"
    stow -D $folder -v
done
popd

unlink "$DOTFILES_HOME/nvim/.config/nvim/templates"
