backend = "glx";

# GENERAL
vsync = true;
use-damage = true;

# PERFORMANCE
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
glx-swap-method = "buffer-age";
glx-copy-from-front = false;

refresh-rate = 0;

mark-wmwin-focused = true;

xrender-sync-fence = true;
# detect-transient = true;

