# set -ga terminal-overrides ",screen-256color*:Tc"
# set-option -g default-terminal "screen-256color"
set -a terminal-features "tmux-256color:RGB"
set-option -g default-shell $SHELL
set-option -g focus-events on
set -g mode-keys vi
set -s escape-time 0

# SET PREFIX KEY
# unbind C-b
# unbind C-Space
# set-option -g prefix C-Space
# bind-key C-Space send-prefix
set -g prefix C-SPACE

# Mouse support
set -g mouse on

# Status line
set -g status-style 'bg=#333333 fg=#5eacd3'

# Base index 1 instead of default 0
set -g base-index 1
set -g pane-base-index 1

set -g renumber-windows on


#####################
#    KEY BINDING    #
#####################
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'

bind-key r source-file $XDG_CONFIG_HOME/tmux/tmux.conf \; display "Reloaded!" # RELOAD config file
bind G neww -n "lazygit" -c "#{pane_current_path}" lazygit
bind E show-environment -g

# vim-like pane switching
# bind-key -r ^ last-window
# bind-key -r k select-pane -U
# bind-key -r j select-pane -D
# bind-key -r h select-pane -L
# bind-key -r l select-pane -R
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# splitting
bind-key | split-window -hc "#{pane_current_path}"
bind-key - split-window -vc "#{pane_current_path}"

# Swap window
bind -r '<' swap-window -d -t -1
bind -r '>' swap-window -d -t +1

# CUSTOM KEY BINDING
bind-key -r f neww "${DOTFILES}/scripts/tmux-sessionizer.sh"
bind-key -r i neww "~/.local/bin/cht.sh"

