listener {
    # Thời gian chạy lệnh khóa màn hình (tính bằng giây, 300 giây = 5 phút)
    timeout = 300
    # Lệnh thực hiện khóa màn hình khi hết thời gian nhàn rỗi
    on-timeout = swaylock
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on          
}
