#!/usr/bin/env bash

BATTERY_PATH='/sys/class/power_supply/BAT0'

if [ ! -d "$BATTERY_PATH" ]; then
    echo "No Battery"
    exit 1
fi

PERCENT=$(cat "$BATTERY_PATH/capacity")
STATUS=$(cat "$BATTERY_PATH/status")

ICON='BAT'  # Default icon (Unknown)

case "$STATUS" in
    'Charging') ICON='CHR' ;;     # Charging icon
    'Not charging') ICON='BAT' ;;  # Discharging icon
    'Full') ICON='FULL' ;;        # Full battery icon
esac

echo "$ICON $PERCENT%"

